### ISSUE TITLE
upgrade requests to >=2.31.0

### ISSUE THREAD

**Issue by lmgarret** [byteface/domonic#63]
Hi! `requests` 2.31.0 addresses some security issues that affect versions v2.3.0 and v2.30.0. Upgrading `domonic`'s dependency would be nice.
For context, we use `domonic` as a dev dependency in our stack to locally produce some html documentation files, but cannot upgrade `requests` since domonic has the requirement `requests~=2.28.0`.

Which makes me think, would it be possible to make `requests` as an extra dependency for people who want to load remote html? e.g. in our case we're not interested in this feature, but I see what it could be used for and I would find it reasonable to `pip install domonic[requestes]` if I wanted to use this feature.

Thanks!

**Comment by byteface** [comment]
FAILED tests/test_javascript_date.py::TestCase::test_getTime - assert 787021200000 == 787017600000
FAILED tests/test_javascript_date.py::TestCase::test_javascript_date - assert 1 == 0
FAILED tests/test_webapi.py::TestCase::test_xpath - requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='eventual.technology', port=80): Max retries exceeded with url: / (Caused by Co...
================================================== 3 failed, 506 passed in 548.60s (0:09:08) ===================================================

Need to investigate the failed tests here....

**Comment by byteface** [comment]
resolved
